name: Python Versions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv
          version: "0.7.5"
          python-version: ${{ matrix.python-version }}
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv

      - name: Install Dependencies
        run: |
          make install
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv

      - name: Format
        run: |
          make format
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv

      - name: Lint
        run: |
          make lint
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv

      - name: Test
        run: |
          make test
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/.venv
